/*
 Data Import and Table Creation
Successfully imported 5 CSV files into SQL Server to create the foundational database tables:
Orders
Customers
Deliveries
Restaurants
Riders
Adjusted data types during import to ensure compatibility and efficiency (e.g., INT, VARCHAR, DATE).
Applied necessary constraints such as PRIMARY KEY to enforce data integrity and uniqueness.
*/

-- Exploratory Data Analysis

-- The last order's date in the Orders table

-- here we are considering Today's date as this

-- Q1 Write a query to find the top 5 most frequently ordered dishes by customer called "Arjun Mehta" in the last 2 year

--Q2 Popular Time slot: Identify the time Slots during which the most orders are placed. based on 2 hours interval

-- Q3 Order Value Analysis: Find the Average Order value per customer who has placed more than 750 orders
-- Return Customer_name, and AOV(Average Order Value)

--Q4  High Value Customers: List the Customers who have spent more than 100K in total on food orders.
-- Return customer_name, and customer_id

-- Q5 Orders without Delivery: Write query to find orders that were placed but not delivered.
-- Return each restaurant name, city and number of not delivered orders

-- Q6 Restaurant Revenue Ranking: Rank restaurants by their total revenue from the last year. 
--including their name, Total Revenue, and rank within their city

-- Top 3 Restaurant in their City based on Their Highest Revenue Revenue

-- Q7 Most popular dish by City:
--Identify the Most Popular dish in each city based on the number of orders

--Q8 Customer Churn
-- Find Customers who haven't placed an order in 2024 but did in 2023

--Q9 Cancelled Rate Comparison:
-- Calculate and Compare the order Cancellation rate for each restaurant between the currrent year 
-- and previous year 
-- Solution:Step 1 

-- Final Solution of Quesiton 9, Rearranging CTEs

-- Q10 Rider Average Delivery Time
-- Determine each rider's average delivery time

-- Q11 Monthly Restaurant Growth Ratio:
-- Calculate each restaurant's growth ratio based on the total number of delivered orders since its joining

--Q12 Customer Segmentations:
-- (1) Segment Customers into "Gold" or "Silver" groups based on their total spending
-- (2) Compare to the Average Order Value
-- If Customer's total spending  exceeds AOV Label them with gold other wise label them as silver
-- Write a Query to Determine each segment's total number of orders and total revenue

-- Q13 Rider Monthly Earning:
-- Calculate each rider's total monthly earnings, assuming they earn 8% of the Delivered Order Amount

-- Q 14 Rider Rating Analysis:
-- Find the number of 5 Star. 4 star, and 3 star rating Each riders has.
-- Riders recieve this rating based on delivery time
-- IF orders are delivered less than 15 Minutes of order recieved time the rider get 5 star rating.
-- IF they delivery is 15 to 20 Minute then they get a 4 star rating
-- IF they deliver after 20 Minute they get 3 star rating.

-- Q 15 Order Frequency by Day:
-- Analyze order frequency per day of the week and identify the peak day for each restaurant

-- Q16 Customer Lifetime value(CLV)
-- Calculate the Total Revenue Generated by each customer over all their orders

-- Q 17 Monthly Sales Trends:
-- Identify Sales Trends by Comparing each month's total Sales to the previous months

-- Q 18 Rider Efficiency
-- Evaluate rider Efficiency by determining Average Delivery times and Identifying those with lowest 
-- And highest Average Delivery time

-- Q19 Order Item Popularity:
-- Track the Popularity of specific order items over time and identify seasonal demand spikes

-- Q 20 Rank each City based on the Total revenue for last year 2023
